### ISSUE TITLE
Oracle bug that might be fixed in newer version?

### ISSUE THREAD

**Issue by beikov** [gvenzl/oci-oracle-xe#100]
I ran into a segmentation fault on Oracle 18 and was curious if this might have been fixed in a new version that the images haven't updated to yet. Here is the reproducer:

```sql
CREATE TABLE Pickup(
  id NUMERIC(10,0) NOT NULL PRIMARY KEY,
  owner varchar2(40)
)
CREATE TABLE Car(
  id NUMERIC(10,0) NOT NULL PRIMARY KEY
)

insert into Pickup(id,owner) 
select c1_0.id,cast(null as varchar2(4000 char)) from Car c1_0 
union all 
select c2_0.id,cast(null as varchar2(4000 char)) from Car c2_0 
order by 1 
fetch first 1 rows only
```

Fails with the following:

```
Exception [type: SIGSEGV, Address not mapped to object] [ADDR:0x90] [PC:0x41AC124, kkqteCheckValidity()+3636] [flags: 0x0, count: 1]
Errors in file /opt/oracle/diag/rdbms/xe/XE/trace/XE_ora_494.trc  (incident=401) (PDBNAME=CDB$ROOT):
ORA-07445: exception encountered: core dump [kkqteCheckValidity()+3636] [SIGSEGV] [ADDR:0x90] [PC:0x41AC124] [Address not mapped to object] []
Incident details in: /opt/oracle/diag/rdbms/xe/XE/incident/incdir_401/XE_ora_494_i401.trc
Use ADRCI or Support Workbench to package the incident.
See Note 411.1 at My Oracle Support for error and packaging details.
Dumping diagnostic data in directory=[cdmp_20220404092259], requested by (instance=1, osid=494), summary=[incident=401].
```

I'm not an Oracle customer so I don't know where else to report this to. Note that wrapping the query group like this works:

```sql
insert into Pickup(id,owner) 
select * from (
select c1_0.id,cast(null as varchar2(4000 char)) from Car c1_0 
union all 
select c2_0.id,cast(null as varchar2(4000 char)) from Car c2_0 
) t
order by 1 
fetch first 1 rows only
```

**Comment by mprins** [comment]
>  this might have been fixed in a new version

a new version would be 21 xe which is available, as it says in the support message on https://www.oracle.com/database/technologies/xe18c-downloads.html 

> Support
Oracle Database Express Edition (XE) is a community supported edition of the Oracle Database family. Please go to the [Oracle Database XE Community Support Forum](https://community.oracle.com/community/database/developer-tools/oracle_database_express_edition_xe/overview) for help, feedback, and enhancement requests.
>
> Note: Oracle Support Services only provides support for Oracle Database Enterprise Edition (EE) and Oracle Database Standard Edition 2 (SE2) in conjunction with a valid Oracle Database Technical Support agreement. No patches will be provided for Oracle Database Express Edition.

**Comment by mprins** [comment]
https://www.oracle.com/database/technologies/xe-downloads.html that provides the 21C express downloads has the same support message provides downloads of Sept / Oct  2021

**Comment by gvenzl** [comment]
Hi @beikov,

I'm afraid that bug is still present in 21c as well:

```
Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production

SQL> insert into Pickup(id,owner)
select c1_0.id,cast(null as varchar2(4000 char)) from Car c1_0
union all
select c2_0.id,cast(null as varchar2(4000 char)) from Car c2_0
order by 1
fetch first 1 rows only;
insert into Pickup(id,owner)
*
ERROR at line 1:
ORA-03113: end-of-file on communication channel
Process ID: 267
Session ID: 48 Serial number: 15842
```

As @mprins already pointed out, support for XE is only available via the Forum (note, you have not posted your issue in the correct forum either. The forum for XE is https://community.oracle.com/tech/developers/categories/oracle_database_express_edition_xe)

The issue appears to be with the `fetch first 1 rows only` clause:

```
insert into Pickup(id,owner)
select c1_0.id,cast(null as varchar2(4000 char)) from Car c1_0
union all
select c2_0.id,cast(null as varchar2(4000 char)) from Car c2_0
order by 1;

0 rows created.
```

May I ask what you are trying to accomplish with that query?
The example raises several questions.
1) For example, why do a union all on the same table and then just fetch the first 1 row anyway?
1) Why a `union all` and not just `union`?
1) Why a `union all` at all given it's the very same query and from the same table?
1) Why cast a null to varchar2 (which doesn't do anything, a null cannot be cast into anything but null)?
1) Why try cast into varchar2(4000) when the table only holds varchar2(40)?
1) Why not just do `''` instead of `cast(null ...`?

From what I see from the example, the entire query could just be

```
INSERT INTO pickup (id, owner)
SELECT c.id, '' FROM car c
 FETCH FIRST 1 ROW ONLY;
```

**Comment by beikov** [comment]
>May I ask what you are trying to accomplish with that query?

This is just a synthetic query that I created to showcase some Hibernate features, please don't worry about the logic of it, as it has none :)

>As @mprins already pointed out, support for XE is only available via the Forum (note, you have not posted your issue in the correct forum either. The forum for XE is https://community.oracle.com/tech/developers/categories/oracle_database_express_edition_xe)

Thanks, I reposted it there: https://community.oracle.com/tech/developers/discussion/4497048/oracle-bug-that-might-be-fixed-in-newer-version

**Comment by christianshay** [comment]
I have filed an initial bug for this, will let you know when I find out more.

**Comment by gvenzl** [comment]
Thanks a lot, @beikov,

I spoke with the developer this week and this bug has not yet been reported nor addressed in newer versions of the Oracle Database either.
The developer is confident that we will have this fixed in the next version of the Oracle Database.
Until then, please use the workaround you have already found.

Thank you very much for reporting this bug and helping make Oracle Database better!
I owe you a beverage of your choice! :)

**Comment by beikov** [comment]
Lass es mich wissen wenn du in Wien oder Linz bist 😉

**Comment by gvenzl** [comment]
Linz ist normalerweise eher der Fall ;)
Irgendwann mal Anfang August, wenn die Welt bis dahin noch steht :)

**Comment by gvenzl** [comment]
Hey @beikov,

Given that this is a confirmed bug in the Oracle Database and now with Oracle Database Development, I would like to go ahead and close this question, as there is nothing else that can be done here anymore. :)

Does that sound good to you?
