### ISSUE TITLE
Strange problems if the CBD is restarted to apply some system changes

### ISSUE THREAD

**Issue by stronk7** [gvenzl/oci-oracle-xe#111]
Hi,

first of all, thanks for maintaining these images, they are really useful! We (Moodle) are moving away from 11g and direct jumping into 21c (XE in both cases) and, while the images are working perfectly, we are facing an strange problem that I wanted to share here (note that, maybe it's not a problem of the images, but something I'm doing incorrectly, although I'm unable to find it).

What we are doing, more or less is:

1. Create a PDB (called "MDB", with all the datafiles in a special directory ("mdb"). We do this to be able to mount that directory as tmpfs and get all the speed benefits we can from that.
2. Drop other PDBs that come with the image (XEPDB1, PDB$SEED). This is purely optional, and our first intention was to make it as part of the docker image generation, together with 1. above, so we get a lighter image.
3. Finally, apply a few system settings that can help to get better performance. And then, restart the CDB.

The problem we are facing is that, every time that we restart the CDB (no matter if the PDBs also have been shutdown or no)... on restart, the database is unable to find the "mdb" files and there are all sort of errors.

I've tried doing it manually, doing it on image build, also in init script ([link to current init script](https://github.com/moodlehq/moodle-db-oracle/blob/21c/root/container-entrypoint-initdb.d/01-mdb.sql#L47-L61)), with and without tempfs, doing it swapping points 1 and 3 above, also trying to make everything in the CDB, not using PDBs at all... and always, always... I get errors and the database cannot start.

Can you imagine any obvious reason for that? I've ended disabling the system settings and we are using it that way... but it's a pity that we cannot configure the CDB (that requires restarting).

Has anybody been able to restart the CDB in their images or ini scripts? I'm asking here because have tried all the combinations I've been able to imagine and haven't been able to find any information out there (about it being a known issue...).

Again, note that this may be not a problem related with the (cool) images, so feel free to close it. Just I wanted to share the problem in case there is something obvious I'm missing.

TIA and ciao :-)

**Comment by gvenzl** [comment]
Hi @stronk7,

Thanks a lot for using these images!

I just went through your current init script and beyond and it works just fine on my end:

```
bash-4.4$ sqlplus / as sysdba

SQL*Plus: Release 21.0.0.0.0 - Production on Sat Jun 4 18:09:17 2022
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle.  All rights reserved.


Connected to:
Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0

SQL> CREATE PLUGGABLE DATABASE MDB
    ADMIN USER moodle IDENTIFIED BY "m@0dl3ing"
        ROLES=(CONNECT, RESOURCE, DBA)
        DEFAULT TABLESPACE users
            DATAFILE '/opt/oracle/mdb/users01.dbf' SIZE 384M AUTOEXTEND ON MAXSIZE UNLIMITED
    PATH_PREFIX = '/opt/oracle/mdb'
    FILE_NAME_CONVERT = (
        '/opt/oracle/oradata/XE/pdbseed',
        '/opt/oracle/mdb')
    NOLOGGING;

Pluggable database created.

SQL> ALTER PLUGGABLE DATABASE MDB OPEN;

Pluggable database altered.

SQL> ALTER PLUGGABLE DATABASE MDB SAVE STATE;

Pluggable database altered.

SQL> ALTER PLUGGABLE DATABASE XEPDB1 CLOSE;

Pluggable database altered.

SQL> DROP PLUGGABLE DATABASE XEPDB1 INCLUDING DATAFILES;

Pluggable database dropped.

SQL> ALTER SESSION SET "_oracle_script" = TRUE;

Session altered.

SQL> ALTER PLUGGABLE DATABASE PDB$SEED CLOSE;

Pluggable database altered.

SQL> DROP PLUGGABLE DATABASE PDB$SEED INCLUDING DATAFILES;

Pluggable database dropped.

SQL> ALTER SESSION SET CONTAINER = MDB;

Session altered.

SQL> ALTER DATABASE DATAFILE '/opt/oracle/mdb/system01.dbf' RESIZE 384M;

Database altered.

SQL> ALTER DATABASE DATAFILE '/opt/oracle/mdb/undotbs01.dbf' RESIZE 64M;

Database altered.

SQL> ALTER DATABASE TEMPFILE '/opt/oracle/mdb/temp01.dbf' RESIZE 64M;

Database altered.

SQL> ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

Profile altered.

SQL> GRANT CREATE SESSION TO moodle WITH ADMIN OPTION;

Grant succeeded.

SQL> GRANT UNLIMITED TABLESPACE TO moodle;

Grant succeeded.

SQL> GRANT EXECUTE ON DBMS_LOCK to moodle;

Grant succeeded.

SQL> SHUTDOWN IMMEDIATE;
Pluggable Database closed.
SQL> STARTUP;
Pluggable Database opened.
SQL> ALTER SESSION SET CONTAINER = CDB$ROOT;

Session altered.

SQL> ALTER SYSTEM SET FILESYSTEMIO_OPTIONS = DIRECTIO SCOPE = SPFILE;

System altered.

SQL> ALTER SYSTEM SET disk_asynch_io = FALSE SCOPE = SPFILE;

System altered.

SQL> ALTER SYSTEM SET INMEMORY_SIZE = 256M SCOPE = SPFILE;

System altered.

SQL> SHUTDOWN IMMEDIATE;
Database closed.
Database dismounted.
ORACLE instance shut down.
SQL> STARTUP;
ORACLE instance started.

Total System Global Area 1237316312 bytes
Fixed Size		    9695960 bytes
Variable Size		  276824064 bytes
Database Buffers	  679477248 bytes
Redo Buffers		    2883584 bytes
In-Memory Area		  268435456 bytes
Database mounted.
Database opened.

--==============================--
--====== END OF INIT SCRIPTS =======--

-- PDB is live and well
SQL> show pdbs;

    CON_ID CON_NAME			  OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
	 4 MDB				  READ WRITE NO
-- I can switch into the PDB
SQL> alter session set container = mdb;

Session altered.

-- I can create  a table for user moodle 
SQL> create table moodle.test (id number) tablespace users;

Table created.

-- I can insert a row into that table

SQL> insert into moodle.test (id) values (1);

1 row created.

SQL> commit;

Commit complete.

SQL> select * from moodle.test;

	ID
----------
	 1

-- Let's restart and see whether the data, i.e. the one row remains there

SQL> alter session set container=cdb$root;

Session altered.

SQL> shutdown immediate;
Database closed.
Database dismounted.
ORACLE instance shut down.
SQL> startup;
ORACLE instance started.

Total System Global Area 1237316312 bytes
Fixed Size		    9695960 bytes
Variable Size		  310378496 bytes
Database Buffers	  645922816 bytes
Redo Buffers		    2883584 bytes
In-Memory Area		  268435456 bytes
Database mounted.
Database opened.

-- Restarted, let's go into the MDB PDB again
SQL> alter session set container=mdb;

Session altered.

-- Select from the table, the PDB, table and row are all still there.

SQL> select * from moodle.test;

	ID
----------
	 1

SQL>
```

What errors are you getting?

My hunch is that as you are using a tmpfs, the tmpfs drops everything that belonged to the process once the process is gone. So as you restart your database, the processes are all gone, of course, and anything on tmpfs will be purged as well.
But you said that you tried with and without tmpfs so that cannot really be it either, can it?

In the end, the real question is whether the data files are still there (or accessible) under `/opt/oracle/mdb` after you restarted the database. If not, then obviously that's a problem. The next question then would be, why are they gone (or no longer accessible).

Btw, I've spotted a couple of unnecessary steps in your init script. Happy to share some feedback on that as well, if you'd like.

**Comment by stronk7** [comment]
Hi @gvenzl ,

many thanks for the the time and the complete report above!

I must confess that I did so many attempts, that right now, I cannot guarantee which ones I did with tmpfs and which ones without it.

My first attempt was to, simply, mount the whole CDB (including both XEPDB1 and PDB$SEED) in tmpfs, using softlinks, but that did not work (like it was with Oracle 11g). That's pretty much the reason I went towards the route of creating a new PDB ("MDB") on top of an already mounted tmpfs, using:

```
docker run --detach --name xxx --network xxxx --tmpfs /opt/oracle/mdb --shm-size=2g ....
```

So, whenever docker runs the image, it creates the tmpfs mount point and then, the init script above creates the "MDB" database there. And that is the attempt that for sure doesn't support a CDB restart.

I'm not sure if I understand the point about the tmpfs mount being purged when the CDB is restarted, I would say that everything continues being there (@ `/opt/oracle/mdb`), the container has not been stopped. Just Oracle don't like the data files for some reason after the restart (I'm afraid, I don't have the exact errors at hand, but will rerun it tomorrow and report them).

Also, note that I'm using docker desktop for mac (my dev environment) and, AFAIK, docker support for tmpfs is not "real" on macs, but simulated (to provide cross-os compatibility). I still have to run the image in a real linux iron. Just in case at the end everything is a bug in the docker desktop for mac implementation!

And about the unnecessary steps, of course, they are welcome. Note I went adding and adding stuff from my original idea (new PDB, file specs...) to the current one, just to see if any of them helped solving the problem.

Again, many thanks!

I'll try to run the tests under linux, paying attention to the tmpfs/non tmpfs combinations... and will report here.

Ciao :-)

**Comment by stronk7** [comment]
Hi again @gvenzl ,

I've finally be able to run some more tests and capture results properly agains our CI (linux) infrastructure. Some points:

1. I've verified @ CI infratructure that the use of tmpfs and restarting the DB (needed to apply some system variables) are incompatible. So it was not a local (Mac Docker Desktop) case, but reproducible on stock/proper docker.
2. I've run tests with tmpfs and without the variables. They ran ok.
3. I've run tests with the variables and without tmpfs. They ran ok.
4. I've run tests without the variables and without tmpfs. The ran ok.
    ^^^ All them (2, 3 and 4) got very similar times, only 4 was slightly better (but Oracle jobs times are highly random - between 3h and 4h  with a worker only running that job). So no clear difference.
5. I've also run some 11g runs, with the same system settings and with tmpfs (that version allows both to be used together, in fact that's what we have right now in our CIs)
   ^^^ 11g are 30m-60m quicker than 21c ones (again, randomness is a factor to consider).

Here there are a couple of runs (still running at the time of writing this):
- 21c: https://ci.moodle.org/job/DEV.02%20-%20Developer-requested%20PHPUnit/7293/
- 11g: https://ci.moodle.org/job/DEV.02%20-%20Developer-requested%20PHPUnit/7294/

Specially because each attempt takes 5-10 mins to get the database and the site installed, I'm going to consider the current 21c Oracle image, without tmpfs and with the system variables like the one to go to our prod CI. If later we find a way to tune/improve it, great, if not... it's a pity but...

For the records, this is our current 21c script (I've moved back to use CDB instead of PDB, just to keep the configuration of jobs being the same for all our Moodle versions, there was not benefit on using the PDB, so far (because tmpfs on it has been discarded):

https://github.com/moodlehq/moodle-db-oracle/blob/21c/root/container-entrypoint-initdb.d/01-mdb.sql#L47-L61

Worth mentioning a couple of details:

- Trying to setup `INMEMORY_SIZE` leaded to horrible results, with sequences "consuming" values in unexpected ways, leading to a good number of failures, so I had to finally disable it. I really didn't look what's needed to use that setting, so surely it was my fault to, happily, introduce it without too much knowledge.
- In logs... I see some information like this, after the final startup:
```
Completed: ALTER DATABASE OPEN
2022-06-10T10:12:03.354435+00:00
 : 
QPI: opatch executable does not exist, opatch
 : 
QPI: OPATCH_INST_DIR not present:/opt/oracle/product/21c/dbhomeXE/OPatch
Unable to obtain current patch information due to error: 20013, ORA-20013: DBMS_QOPATCH ran mostly in non install area
ORA-06512: at "SYS.DBMS_QOPATCH", line 2327
ORA-06512: at "SYS.DBMS_QOPATCH", line 854
ORA-06512: at "SYS.DBMS_QOPATCH", line 634
ORA-06512: at "SYS.DBMS_QOPATCH", line 2309
```
And I'm not sure what's that about, apparently it doesn't affect to anything, but I'd say that I don't see it always.

And that's all. Again, thanks for your images and support, they really have enabled us to go with 21c quicker!

Ciao :-)

**Comment by gvenzl** [comment]
Hi @stronk7,

Thanks for your additional tests and insights into this!

You can safely ignore the QPI opatch error.
The database just tries to retrieve all the patches installed in the environment to print them into the alert.log, however, to save space and because XE doesn't allow for patching anyway, none of the components are available and hence the error that the executable nor directory can be found.
The error will not impact anything other than causing this message in the log.

`INMEMORY_SIZE` was one of the things I wanted to mention. [`INMEMORY_SIZE`](https://docs.oracle.com/en/database/oracle/oracle-database/21/refrn/INMEMORY_SIZE.html) is only a parameter to allocate memory for the in-memory columnar store. But that feature is really only useful when you try to run aggregations that would benefit from a columnar rather than row-based layout of your data. Furthermore, tables would need to be enabled/loaded into that columnar store in the first place, so basically, this doesn't do anything but take away some memory for the rest of the database.
I am curious, however, that you say that when you set that parameter, sequences are consuming values in unexpected ways. The parameter itself has no implications for sequences as they cannot be loaded into the columnar store.
I wonder whether there is some side effect that is taking place there.
Do you happen to have more information on the error?

Regarding your setup itself, I think what you have now is fine.
I cannot see any benefit for you dropping the PDBs `XEPDB` and `PDB$SEED`.
They are already there in the image, unless you add more files in the container and you do want to reuse the space, there doesn't seem to be an apparent benefit for that. On the contrary, your setup will have to wait a bit longer for these to be closed and dropped.

Interesting that Async I/O causes performance degradation but yeah, depending on the underlying filesystem that can be, of course.

I did look at the builds you posted above but I can't really extract any useful information (not really a Jenkins guy, sorry).
I can see that the Timings show `Building 4hr 28min` and `Building 3hr 43min` but other than that, there is very little that shows what is going on.
I tried to drill down in the Test Results but there I also just see, e.g. `accesslib_test 27min` and `accesslib_test 13min`.

If you have some more details on how these tests interact with the database itself and how much time is spent on what tasks, we may be able to tune it a bit further.

**Comment by stronk7** [comment]
Hi,

thanks for your comments.

1) Nice to know about the patches error(s) being ignorable.

2) About INMEMORY_SIZE, yeah, I was planning to see if putting some of our tables/columns there would produce any benefit, but reverted the initiative because of the "strange" errors happening with it enabled.

About those errors, you can see, for example, [this run|https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/7287/] (it has the INMEMORY_SIZE enabled). And the run ended with ~ 3800 failures!

By comparison, the [very next run](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/7293/), which only difference is that the INMEMORY_SIZE was commented out, ended with "only" 3 failures (that we are investigating right now, because they are certainly mysterious - and pass perfectly with 11g). Anyway that's another story, heh.

Back to the job with 3800 failures, and related with the sequences problem... if you look to the [full console](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/7287/consoleFull”, and then go to `8. Section Initialising test environment` -> `Show details` . After installing all the composer dependencies... the installation (database-wise) of the testing site begins... and, there, you can see the warnings:
```
-->System
!! Unexpected id generated for the Admin account. Your database configuration or clustering setup may not be fully supported !!
!! Nonconsecutive id generated for the Admin account. Your database configuration or clustering setup may not be fully supported. !!
```

And those warnings correspond exactly with this piece of code:

https://github.com/moodle/moodle/blob/master/lib/db/install.php#L241-L246

There, we just insert a couple of records in the (Moodle) users table, in the same script, same session and database connection. And, if it's detected that the 2nd user insertion "id" (that is fed by a sequence) is not consecutive with the 1st inserted one... the warns happen. In this case, they were being inserted with id = 1 (1st user) and id = 21 (2nd user). And all our sequences have 20 values cached.

That was just the first thing I noticed with INMEMORY_SIZE enabled. As said, the number of errors was so big that I just commented out the experiment.

3) Yeah, I will leave the PDBs there, there isn't benefit in removing them. In fact, I want to verify if they provide quicker access to dictionary tables, because we use them quite a lot, normally cached information, but not in unit tests executions where the caches are reset on every test. And performing some basic monitoring with `V$SQL` it shows that those dictionary searches are consuming quite a lot of time, when using the CDB. So, maybe at the end I'll use the PDB if it performs better. Note I've already tried running statistics on dictionary tables and so on, to see if results improved, but, as far as there are many DDL changes in our tests... I imagine that's not completely effective (at very least, there wasn't any clear gain running the tests after analyse them).

4) And yeah, we are getting 40-60 minutes worse times using 21c than 11c (same iron, same codebase... only changing the docker container between the 2 versions).

5) Only doubt I'm having lately is if, maybe, I've go "too far" and maybe 21c is still relatively new and I should try with Oracle 19c, that is really the one that is going to be our requirement for the next Moodle versions. I just picked 21c because it was XE, slim and public (similar to the one we were using for 11g). Maybe I'll give a try to the official Oracle Database images, from their registry, although it's a pity if we cannot make them public, there are a bunch of sub-products that may need to use them. Note I've not investigated about all this yet, still trying to get 21c passing, because the 19c requirement is going to be in place in few weeks and we need to keep all the jobs passing before then.

And that's all, it's being fun, heh. I really was expecting everything to continue passing and, ultimately, being a bit quicker that the old 11g... but it's not (anyway, that was just a wish, I hope we can, at very least, get it passing, performance is something that can come later).

Ciao :-)

**Comment by gvenzl** [comment]
Hey @stronk7,

Thanks again for all the info, really helpful!

I have a theory but not enough information to prove it (yet) :)
The `-slim` images I've built focus on the smallest possible Docker image size. I have done all sorts of tweaks (fully documented [here](https://github.com/gvenzl/oci-oracle-xe/blob/main/ImageDetails.md#slim-image-flavor-18-slim)) to make them as small and fast starting as possible. That includes some settings overall memory settings and resizing of the redo log journaling files.
My theory is twofold:

1) You are getting all sorts of `checkpoint incomplete` (`output in the $ORACLE_BASE/diag/rdbms/xe/XE/trace/alert_XE.log` file) during your tests because I made the redo logs tiny (just two of them, 10MB each). I spare you the technical details (unless you want to know them) but if you have a lot of transactions going on and these are not sized adequately, you will hit the disk a lot more often than you would like.
2) I still cannot see a connection of setting `INMEMORY_SIZE` to sequences, except that when setting it, it takes away memory for other areas, namely the shared pool and the buffer cache, which I suspect you care most about during your tests (because shared pool deals with SQL statement caching and execution and buffer cache caches your data).

Now, I cannot prove any of this because I do not have enough information and I honestly don't think it is worth your time changing different settings via trial and error, as these tests run for a long time and I'm sure you have better things to do.
Would it be possible in your testing infrastructure to preserve the `$ORACLE_BASE/diag` directory after the tests are done and provide the contents somehow to me (or here)? For now, I'm just curious about `$ORACLE_BASE/diag/rdbms/xe/XE/trace/alert_XE.log` really, so that works too. Even if you can just cat that file somewhere so that it shows up in Jenkins somewhere, that works too.

Btw, regarding the memory, the DB instance doesn't use the entire 2GB that's allowed, only 1.5GB. That too could make things a bit faster if the DB is under memory pressure, but again, I cannot prove that either.

I don't think you have gone too far with 21c. The delta between 21c and 19c is not that big but there is a huge delta between even 18c and 11g. 11g came out in 2007, it's kinda ancient by modern IT standards (although admirable how good of a software it was that folks still use it all over the place today) and a lot has changed in Oracle DB, including the PDBs that came already with 12.1. So there is a lot more going on with 21c (or 19c) than there was with 11g.
However, I can tell you (because of my day job) that 21c did not suffer from performance regressions compared to 11g. Now maybe the workload drives 21c XE towards its resource limits but I doubt that given that these run fine on 11g XE that has even fewer resources (only 1GB of memory, for example).

I'm sure we can sort it out if you are willing to keep looking.
