### ISSUE TITLE
Don't require 2GiB RAM for 18c (or: why?)

### ISSUE THREAD

**Issue by micheljung** [gvenzl/oci-oracle-xe#168]
According to [System Requirements for Oracle Database Express Edition (XE) 18c.](https://www.esolution.ca/oracle-database-xe-system-requirements/), the minimum memory is 1 gigabyte but 2 gigabytes is recommended.

However, this image requires a minimum of 2 GiB:

https://github.com/gvenzl/oci-oracle-xe/blob/dce074aee0b8064db520acdf15c6834d18993afc/container-entrypoint.sh#L321-L329

Why is that, and could it be changed to 1GiB? It makes quite a difference when using the image in CI where multiple builds may run in parallel.

Also, it'd be nice if the error message included what the expected value is. And use the correct suffix `MiB` instead of `MB` ;)

**Comment by gvenzl** [comment]
Hi @micheljung,

The check is there so that if a user decides to give the database 2 GB of RAM he doesn't run into an error because the container itself doesn't have enough memory available. It helps novice users not to have to know the difference between the memory requirements of the software in the container and how much the container itself is allowed to allocate.

The check is just about the maximum allowed memory for the container, not the actual allocation. You can still run 2 Oracle XE instances in 2 containers with 1 GB each.

Fair point about `MB` and `MiB` though I doubt the average user knows their difference. Anyway, will fix that, well spotted.
