### ISSUE TITLE
Getting ORA-29275: partial multibyte character when using gvenzl/oracle-xe:21-slim

### ISSUE THREAD

**Issue by alf** [gvenzl/oci-oracle-xe#180]
We're looking into upgrading from gvenzl/oracle-xe:18-slim to gvenzl/oracle-xe:21-slim, however we get the following error when executing  `CHR(242)` in our procedures. The problem is easy to reproduced by executing the following anonymous block:

```
declare
  x varchar(10);
begin
  x := chr(242);
end;
/
```

In a fresh instance running Oracle 21 XE (`docker run -e ORACLE_RANDOM_PASSWORD=yes -it --rm -p 1521:1521 gvenzl/oracle-xe:21-slim`) this gives:

```
declare
*
ERROR at line 1:
ORA-29275: partial multibyte character
ORA-06512: at line 4


Elapsed: 00:00:00.00
```

In a fresh instance running Oracle 18 XE (`docker run -e ORACLE_RANDOM_PASSWORD=yes -it --rm -p 1521:1521 gvenzl/oracle-xe:18-slim`) this gives:

```
PL/SQL procedure successfully completed.

Elapsed: 00:00:00.00
```

We're unable to find any reason for why this code does not work in Oracle 21. Are we doing something wrong here?

**Comment by gvenzl** [comment]
Hi @alf,

Thanks a lot for using these images!

It appears that there is a behavior change between 18c and 21c, I can make 21c work by using `USING NCHAR_CS`:

```sql
Connected to:
Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0

SQL> declare
  x varchar(10);
begin
  x := chr(242);
end;
/
  2    3    4    5    6  declare
*
ERROR at line 1:
ORA-29275: partial multibyte character
ORA-06512: at line 4


SQL> declare
  x varchar(10);
begin
  x := chr(242 using NCHAR_CS);
end;
/
  2    3    4    5    6
PL/SQL procedure successfully completed.
```

However, I'm not the best person to comment on nationalization and character set questions.
I recommend asking your question over at [asktom.oracle.com](https://asktom.oracle.com) instead.

Meanwhile, I will close the issue here as this has nothing to do with the container images themselves but with the behavior of the Oracle Database.
