### ISSUE TITLE
Remove vendor lock-in feature for 11-slim-faststart

### ISSUE THREAD

**Issue by mysteryboy2000** [gvenzl/oci-oracle-xe#210]
I would like to see an Oracle 11g R2 11-slim-faststart image that removes unnecessary sub-features such as Advanced Queue / APEX server, etc which are unique to Oracle, and leaves only the minimal Oracle Database.

**Comment by mprins** [comment]
This project only produces Oracle Database XE container/docker images for legal reasons, so you will have to place your wish elsewhere

**Comment by gvenzl** [comment]
Actually, these images are primarily here because I needed some Docker images for Oracle Database myself for another project of mine.
Anybody can pull the official images from https://container-registry.oracle.com if they wish to do so.

However, that being said, I have strong opinions on vendor lock-in arguments, and it's highly subjective which features may seem "unnecessary".

The slim images already have components removed with the main goal to make the image size smaller and downloads faster, see [ImageDetails.md](https://github.com/gvenzl/oci-oracle-xe/blob/main/ImageDetails.md).
Users can always opt to build their own image and customize it to their needs.
