### ISSUE TITLE
Upgrade Timezone file

### ISSUE THREAD

**Issue by oscarodrigo** [gvenzl/oci-oracle-xe#223]
Hello, im importing a datapump in the database 21.3.0, but I'm having an error with the timezone version:

![image](https://github.com/gvenzl/oci-oracle-xe/assets/3004619/47805312-eb76-41f2-a2ee-1c44a74e773e)

Do you know how this can be solved?

Thanks

**Comment by gvenzl** [comment]
Hi @oscarodrigo,

Thanks a lot for using these images!

I have checked with my colleague who is responsible for this area and unfortunately there is no fix that can easily be done or provided.

The error that you are seeing happens because you are trying to import data from a database running with a Timezone version file 36 into a database (21c XE) with a Timezone version file 35, which is not allowed and hence this error is raised.
Usually the solution would be to apply a patch to update this Timezone version file to >= 36 but as there are no patches for XE, there is no way of doing that.

A remedy might be to use `gvenzl/oracle-free` instead which delivers the new Oracle Database 23c Free images.

**Comment by oscarodrigo** [comment]
Thanks!
