### ISSUE TITLE
Missing double-quotes for  APP_USER

### ISSUE THREAD

**Issue by JAusD** [gvenzl/oci-oracle-xe#237]
Hi Gerald,
first of all, thx for providing this image!

When i try to start a new container with an APP_USER, startup script fails:

`docker run -d -p 1521:1521 -e ORACLE_PASSWORD=NDU3YmY3 -e APP_USER=my-user -e APP_USER_PASSWORD=my-password gvenzl/oracle-xe:latest-faststart`

results in

> 2023-11-05 20:58:09 Session altered.
2023-11-05 20:58:09 
2023-11-05 20:58:09    CREATE USER my-user IDENTIFIED BY "my-password" QUOTA UNLIMITED ON USERS
2023-11-05 20:58:09                  *
2023-11-05 20:58:09 ERROR at line 1:
2023-11-05 20:58:09 ORA-00922: missing or invalid option

Executing `CREATE USER my-user IDENTIFIED BY "my-password" QUOTA UNLIMITED ON USERS` directly from sqldeveloper get's the same error.
Using some additional double-quotes like `CREATE USER "my-user" IDENTIFIED BY "my-password" QUOTA UNLIMITED ON USERS` fixes the problem.
I tried to provide those double-quotes via --env but they are removed:
`docker run -d -p 1521:1521 -e ORACLE_PASSWORD=NDU3YmY3 -e APP_USER="my-user" -e APP_USER_PASSWORD=my-password gvenzl/oracle-xe:latest-faststart`
`docker run -d -p 1521:1521 -e ORACLE_PASSWORD=NDU3YmY3 -e APP_USER=\"my-user\" -e APP_USER_PASSWORD=my-password gvenzl/oracle-xe:latest-faststart`

KR, Joachim

**Comment by JAusD** [comment]
Problem is/was using a username that contains "-" like my-user. 
Using my_user instead needs no double quotes. So please consider that as an enhancement rather then a bug.
KR, Joachim

**Comment by gvenzl** [comment]
Hi @JAusD,

Thanks a lot for using these images!

### Background

The reason why a username with `-` doesn't work without the double quotes is that it is interpreted as an operator, i.e. the minus `-` operator.
As SQL allows you to write queries like

```sql
SQL> select 2-1 from dual;

       2-1
----------
	 1
```

or

```sql
SQL> create table foo (num1 int, num2 int);

Table created.

SQL> insert into foo values (2, 1);

1 row created.

SQL> select num1-num2 from foo;

 NUM1-NUM2
----------
	 1
```

or even

```sql
SQL> var b1 number;
SQL> var b2 number;
SQL> exec :b1 := 2;

PL/SQL procedure successfully completed.

SQL> exec :b2 := 1;

PL/SQL procedure successfully completed.

SQL> select :b1-:b2 from dual;

   :B1-:B2
----------
	 1
```

The same is true for `+`, `*`, `/`:

```sql
SQL> create user my+user identified by foo;
create user my+user identified by foo
              *
ERROR at line 1:
ORA-00922: missing or invalid option


SQL> create user my/user identified by foo;
create user my/user identified by foo
              *
ERROR at line 1:
ORA-00922: missing or invalid option


SQL> create user my*user identified by foo;
create user my*user identified by foo
              *
ERROR at line 1:
ORA-00922: missing or invalid option
```

So you can very quickly run into situations where my-user could be interpreted as `my`-`user`.
Of course, for a `CREATE USER` statement it might be more obvious what's wanted here, but you can imagine how quickly it would get confusing when having a column called `my-quantities`, i.e. how would that be interpreted:

```sql
select my-quantities from foo;`
```

Should that be interpreted as `my`-`quanities` or not the column name? What if there are all columns `my`, `quantities` and `my-quantities` in the table, which ones should be picked?

At a higher level, user names, column names, table names, etc. are all identifiers and to avoid confusion or unexpected behavior, all identifiers follow the same rules, hence, by default, identifiers cannot contain any arithmetic operators (`+`, `-`, `*`, `/`) among many other things.
For the whole list, see [Database Object Names and Qualifiers](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/Database-Object-Names-and-Qualifiers.html)

The important parts are these:

> 6. Nonquoted identifiers must begin with an alphabetic character from your database character set. Quoted identifiers can begin with any character.
>
> 7. Nonquoted identifiers can only contain alphanumeric characters from your database character set and the underscore (_), dollar sign ($), and pound sign (#). Database links can also contain periods (.) and "at" signs (@). Oracle strongly discourages you from using $ and # in nonquoted identifiers.
> 
>     Quoted identifiers can contain any characters and punctuations marks as well as spaces. However, neither quoted nor nonquoted identifiers can contain double quotation marks or the null character (\0).

And:

> Note: Oracle does not recommend using quoted identifiers for database object names. These quoted identifiers are accepted by SQL*Plus, but they may not be valid when using other tools that manage database objects.

Now, that was a lot of background, and I hope it wasn't too much off-topic, but coming back to this:

### Request being made

Unfortunately, putting double quotes around the user name has a couple of implications.
One already outlined above is that you will then always have to use double quotes to refer to that user, e.g:

```sql
SQL> create user "my-user" identified by foo;

User created.

SQL> grant connect to my-user;  -- invalid
grant connect to my-user
                   *
ERROR at line 1:
ORA-00933: SQL command not properly ended

SQL> grant connect to "my-user"; -- valid

Grant succeeded.

SQL> create table my-user.test(id int);  -- invalid
create table my-user.test(id int)
               *
ERROR at line 1:
ORA-00922: missing or invalid option


SQL> create table "my-user".test(id int); -- valid

Table created.

SQL> select * from my-user.test; -- invalid
select * from my-user.test
                *
ERROR at line 1:
ORA-00933: SQL command not properly ended


SQL> select * from "my-user".test;  -valid

no rows selected
```

The other important thing is that once double quoted, the identifier has to be presented in exactly that way. In other words, your username is now also case-sensitive:

```sql
SQL> create user test identified by test;

User created.

SQL> grant connect to TEST; -- note the uppercase TEST here while the user was created as test

Grant succeeded.

SQL> conn test/test@xepdb1;
Connected.
```

```sql
SQL> create user "test1" identified by test;

User created.

SQL> grant connect to test1; -- Error, because the user name (and all other identifiers) is automatically upper-cased 
grant connect to test1
                 *
ERROR at line 1:
ORA-01917: user or role 'TEST1' does not exist
```

More importantly, it affects your connect string as well:

```sql
SQL> conn test1/test@xepdb1 -- does not work, because it is implicitly be uppercased
ERROR:
ORA-01017: invalid username/password; logon denied


Warning: You are no longer connected to ORACLE.
SQL> conn "test1"/test@xepdb1 -- does work
Connected.
```

So by putting a double quote around the user name, we would impact every other user that created users in lowercase, e.g. `-e APP_USER=test`, but then connect to it with `TEST`, `TeST`, `tesT`, all of which are possible and allowed currently:

```sql
SQL> conn TEST/test@xepdb1
Connected.
SQL> conn TeST/test@xepdb1
Connected.
SQL> conn tesT/test@xepdb1
Connected.
```

You may ask "Ok, but why the double quotes around the password then?" That is because back in Oracle 11g R2, Oracle went on to use case-sensitive passwords by default and the only way to preserve the case as it has been provided by the user, is by using the double quotes.

### Conclusion

With all that background and details, I'm not very inclined to change the user creation to use double quotes, as it would mean introducing case-sensitive user names, something that is already not recommended as per the Oracle Documentation, with a high potential of impacting other users of these images.
Instead, I recommend instead not to use the `-` character in your usernames but sticking to either `_` or no separator character at all.

What do you think?

**Comment by JAusD** [comment]
Hi Gerald,
thx for your very detailed explanation that gave me a deep insight of Oracle's behaviour and some history!  I've already wondered several times, when quotes are needed and when not, now i know the reason why  ;)

Since i'm only occasionally working with oracle i just didn't think about my naming-pattern and using "_" instead of "-"  is perfectly fine with me. I completely agree with you that this change would possibly do more harm than good.

Thanks for your time and the information provided,
Kind regards, Joachim
