### ISSUE TITLE
Instructions for creating an image with a bundled database for testing

### ISSUE THREAD

**Issue by alf-mindshift** [gvenzl/oci-oracle-xe#28]
Thank you for your great work on creating a slimmed down docker image with Oracle XE 18c.

I was wondering if you have any advice on the best way to extend this image with a bundled database. The use case for this is integration testing of large databases etc where bootup times is important. 

I see two main approaches:

1. Use docker run, mounting the scripts for creating my database into `/container-entrypoint-initdb.d`, wait until completion; shutdown and docker commit
2. Use a Dockerfile and ADD the scripts into `/container-entrypoint-initdb.d`, including a final script that stops the database and trigger container-entrypoint.sh

Neither of these feel very good, however I'm at a loss for a third and better apporach.

**Comment by gvenzl** [comment]
Hi @alf-mindshift,

Thank you very much, I'm glad you like them!

You have a couple of options here, depending on your scenario.

The two options that you have laid out above are definitely valid but I would recommend option No. 2 when considering them, as that one can be easily automated and added to a common (container) toolchain.

An important question is whether you would like to have a customized database as part of the image, or not.

A third approach could be to, for example, create a database with the steps outlined above in No. 1, but instead of doing a `docker commit`, you preserve the customized database in a volume once. The container script is smart enough to check whether there already is an existing database and if so, it will just start that database up. So you could point your container to a volume that already has such a customized database in it, and it will just start that database up for you. The downside, however, is that you will have to have that volume obviously readily available wherever the container will run and clone it each time you want to start another container. Depending on your environment, as I believe some orchestration technologies have such a concept of giving containers cloned images, this may not be much of a downside.

A fourth approach that will give you the fastest startup time and benefit of encapsulation would be to combine No. 2 above and the trick about the volume, i.e.:
1) create the database with everything setup and the DB files pointing to a volume
1) build a new image by copying the database files from that volume into the right place.
1) use that new image

The downside of that approach is that your image on the host will have gotten bigger but when you run that image it will just start up your database, giving you the fastest possible startup time.

As to a fifth approach, Oracle 18c XE also comes with a new technology called "[pluggable databases](https://docs.oracle.com/en/database/oracle/oracle-database/21/multi/plugging-in-a-pdb.html#GUID-5CFC53B9-C457-460A-92A5-DAFDC472F458)" that provides many flexibilities and possibilities when it comes to creating, cloning and relocating databases.
A more database-centric approach could be to create such a pluggable database that comes with all the starter data set included and unplug it as a "gold image". Then on database startup time you just plug in the PDB by providing an additional volume to that container and use the `CREATE PLUGGABLE DATABASE FROM ...` command in a `SQL` script in `/container-entrypoint-initdb.d`. The approach will be similar to approach No. 3 just that it leverages database built-in capabilities and provide you perhaps with better reusability.

Hope this helps!

**Comment by alf-mindshift** [comment]
Yes, this helps a lot. Thank you for enumerating and describing the different options. This was very useful and insightful.  

I like the volume-based approach and the pluggable database-approach and will experiment with this.

**Comment by gvenzl** [comment]
Great, please do let me know how it goes! :)
