### ISSUE TITLE
resetPassword for PDBADMIN user of XEPDB1

### ISSUE THREAD

**Issue by loiclefevre** [gvenzl/oci-oracle-xe#42]
It would allow to not use sys nor system user and still be able to do some administrative tasks.
For versions 18.4 and 21 at least

**Comment by gvenzl** [comment]
Thanks @loiclefevre,

Unfortunately, the `PDBADMIN` user only gets granted the `PDB_DBA` role by default which in itself only has only the following privileges granted:

Roles:
* `CONNECT`

System Privileges:
* `CREATE SESSION`
* `CREATE PLUGGABLE DATABASE`
* `SET CONTAINER` (only in 18c but no longer in 21c)

Object Privileges:
* `SELECT` on `PDB_ALERTS`
* `SELECT` on `PDB_PLUG_IN_VIOLATIONS`

However, because other PDBs cannot be created from within a PDB itself (but only within the CDB), there is actually not much a user can do with this database user other than connecting to the PDB and selecting from the two `PDB_*` views.

I see no real value to reset this user's password as well.
Users can still connect with the `SYSTEM` database user and create or change other database users as they see fit.
