### ISSUE TITLE
Add Oracle Binary download step if the RPM isn't present

### ISSUE THREAD

**Issue by loiclefevre** [gvenzl/oci-oracle-xe#49]
Since no more click is needed, automatic download of the binary RPM file could be added to the buildContainerImage.sh script.

**Comment by gvenzl** [comment]
Unfortunately, that is not a solution that will work forever, as older RPM installer files are being removed from Oracle.
For example, there is no 11g R2 RPM file available anymore (despite it not being click-through free).

However, if the checksum calculation fails, either because the file is not present or the checksum is invalid, `buildContainerImage.sh` could prompt the user whether an automatic download should be attempted. If that fails, it would still be up to the user to provide the installer RPM file.

**Comment by jcrben** [comment]
I needed to build the image for myself and these are the steps I used...

1. From https://docs.oracle.com/en/database/oracle/oracle-database/18/xeinl/procedure-installing-oracle-database-xe.html I found https://docs.oracle.com/en/database/oracle/oracle-database/18/xeinl/procedure-installing-oracle-database-xe.html
2. `curl -L https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-21c-1.0-1.ol8.x86_64.rpm -O` to grab the rpm
3. I got an error about buildah and I was running Ubuntu 20.04 - I found https://gist.github.com/sebastianwebber/2c1e9c7df97e05479f22a0d13c00aeca from Google which directed me to https://fabianlee.org/2022/08/02/buildah-installing-buildah-and-podman-on-ubuntu-20-04/ to get buildah
4. I had to add a trusted CA since I'm working inside a corporate network, so I added a couple lines:
5. COPY Issuing-CA.crt /etc/pki/ca-trust/source/anchors/
6. RUN update-ca-trust

Currently running it and seems to be taking a while, I'll update this when it is done...

**Comment by jcrben** [comment]
So it ran successfully - it was WSL and using too much memory; I added a .wslconfig file to limit memory and avoid going to swap which eliminated the errors.

Still not accessing EM manager tho, even tho I did add a SID_LIST_listener

**Comment by gvenzl** [comment]
Hey @jcrben, which flavor did you build? You need to have `SHARED_SERVERS` > 0 if you want access to the DB Console.

**Comment by jcrben** [comment]
@gvenzl  I ended up having to execute the command suggested at https://github.com/oracle/docker-images/issues/1419#issuecomment-689305485 to see the EM

```
docker exec -it racnode1 /bin/bash
su - oracle
setfacl -R -m u:grid:rwx <XDB wallet location>
eg. setfacl -R -m u:grid:rwx /u01/app/oracle/product/19.3.0/dbhome_1/admin/ORCLCDB/xdb_wallet
```

I think it might have been slightly different from that - I have access to the Oracle Support Center via my employer and reviewed doc ID 2680248.1 on Oracle support

I also mentioned that over at https://github.com/gvenzl/oci-oracle-xe/issues/166

**Comment by gvenzl** [comment]
Cool, thanks a lot for sharing, @jcrben!

**Comment by gvenzl** [comment]
I'm closing this PR as it seems no longer relevant.

Downloading the RPM before the build may adds a nice little touch but ultimately Oracle decides for how long and where to publish these RPMs to, making this proposed mechanism unreliable.
