### ISSUE TITLE
Odd issue with Timezone on 11-full image

### ISSUE THREAD

**Issue by jgebal** [gvenzl/oci-oracle-xe#59]
I'm trying to migrate utPLSQL project  from Travis to GitHub Actions.

When running our own `utPLSQL-cli` from GHActions host to connect to 11-full, I get an error:
```
jdbc:oracle:thin:****/****@127.0.0.1:1521/XE: ORA-00604: error occurred at recursive SQL level 1
ORA-01882: timezone region not found

Could not establish connection to database. Reason: ORA-00604: error occurred at recursive SQL level 1
ORA-01882: timezone region not found
```
See here: https://github.com/utPLSQL/utPLSQL/runs/4318059768?check_suite_focus=true

The 18-small runs just - fine https://github.com/utPLSQL/utPLSQL/runs/4318059793?check_suite_focus=true

I've tried to do the following:
- [adding explicit ORACLE_JDBC path with  ojdbc8 and orai18n] files(https://github.com/utPLSQL/utPLSQL/commit/e94fe62416ee0cabc12e42016d3fcca4e57c9e1b) - that didn't help
- Adding explicit TZ: "Europe/London" in environment variables - this helped

I don't thing that the "workaround" I've found is something usable as  Timezones can be different on different systems.

Can you help understanding why this is happening? Is there something missing/wrong in `11-full` image?

**Comment by gvenzl** [comment]
Hi @jgebal,

I think the issue here is that the timezone that the host is in is not present in the timezone files that the database has.
As timezones change, these timezone files (located under `$ORACLE_HOME/oracore/zoneinfo/`) need to be updated as well. My wild guess here is that the timezone file used back in 11.2.0.2 (~2010) does not have the timezone within in it.

A way to confirm/verify would be to check the timezone on the host:

```bash
cat /etc/timezone
```
and verify whether that timezone is known to the database via:

```sql
SELECT * FROM V$TIMEZONE_NAMES;
```

My expectation is that it is not and hence you get this issue.

`Europe/London` on the other hand is:

```sql
[oracle@2bb41027c1b6 xe]$ sqlplus / as sysdba

SQL*Plus: Release 11.2.0.2.0 Production on Mon Nov 29 01:08:29 2021

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL> select * from v$timezone_names where tzname like '%London%';

TZNAME
----------------------------------------------------------------
TZABBREV
----------------------------------------------------------------
Europe/London
LMT

Europe/London
GMT

Europe/London
BST


TZNAME
----------------------------------------------------------------
TZABBREV
----------------------------------------------------------------
Europe/London
BDST
```

We had a similar issue, if not the same, over at [Quarkus](https://twitter.com/GeraldVenzl/status/1389940601181773827?s=20).
The issue I think is that the JDBC driver implicitly sets the timezone via an `ALTER SESSION SET` command. This can be turned off via a JVM property `oracle.jdbc.timezoneAsRegion=false` hence not producing this issue altogether, which was the route that the Quarkus folks did go.
Same issue on SO with more details: https://stackoverflow.com/questions/9156379/ora-01882-timezone-region-not-found#9177263

**Comment by jgebal** [comment]
Would it make sense to copy newest zoneinfo into DB images when they are getting built?
That way each DB image would have same, up to date timezone tables.

**Comment by gvenzl** [comment]
That is unfortunately not feasible. These timezone files are provided via Oracle Database patches and require e.g. `TIMESTAMP WITH TIMEZONE` columns to be potentially updated. As XE is not eligible for support or patches, it is not possible to update the database with these timezone files during creation or at a later stage.

**Comment by gvenzl** [comment]
Closing the question as the answer has been provided.
