### ISSUE TITLE
Changing SID oracle xe 11

### ISSUE THREAD

**Issue by pidario** [gvenzl/oci-oracle-xe#90]
Apologies if this question has already answered but I couldn't find it anywhere.
I'll start saying that I'm completely new to oracle database, so bear with me, please.
Is there any way to change the SID?

**Comment by gvenzl** [comment]
Hey @pidario,

First of all, let me say thank you very much for using these images!

No worries at all, we have all been there at some point and it's always great to see newcomers! :)

For Oracle Database XE, there is no way to change the SID, it is hard-coded to `XE`.
While for other Oracle Database editions the SID can be freely chosen, it can, in general, not be changed after the initial creation of the database.
However, Oracle Database (since 12c) does provide a mechanism for logical databases, called Pluggable Databases. There you can freely choose a name and a default one is created as `XEPDB1`.
Depending on what your requirements are, that might be a way to go.
I can elaborate more if you tell me what it is that you are after.

Thanks,

**Comment by pidario** [comment]
Thanks for the answer, @gvenzl.
Basically I have a huge project with a whole lot of tests.
Some of these tests expect to connect to a local Oracle db through a custom sid and for some reason to me unknown connection string cannot be parametrized/changed.
I guess my best bet is to instead use a standard edition, it should not be a problem for my company since we have the licenses.
If you can offer another piece of advice it will be very welcome.

**Comment by gvenzl** [comment]
Hi @pidario,

There are a couple of ways to do that. First of all, when connecting to an Oracle database, the connection isn't established directly against a SID or instance anymore ever since Oracle Database 9i (about the year 2000). Back then, Oracle Database introduced [database connection services](https://docs.oracle.com/en/database/oracle/oracle-database/21/netag/identifying-and-accessing-database.html#GUID-5BC573CE-BA12-4251-A987-429095385EC2), allowing applications to be abstracted from the actual instance name. For example, one could connect to `localhost:1521/reporting` and `localhost:1521/sales` ending up on the very same Oracle Database instance `ORCLPROD` (or something, just an example). To make migrations easy back then, by default, a service with the same name as the SID is created, so that legacy applications can continue to connect without requiring a new connect string. Unfortunately, that also makes many believe still today, that one connects to the SID directly and that services do not exist.

You can see that fact in the following output of `lsnrctl status`:

```
bash-4.4$ lsnrctl status

LSNRCTL for Linux: Version 21.0.0.0.0 - Production on 05-MAR-2022 19:54:27

Copyright (c) 1991, 2021, Oracle.  All rights reserved.

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC_FOR_XE)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 21.0.0.0.0 - Production
Start Date                05-MAR-2022 19:49:37
Uptime                    0 days 0 hr. 4 min. 49 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Default Service           XE
Listener Parameter File   /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/5775acfe2c25/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=5775acfe2c25)(PORT=5500))(Security=(my_wallet_directory=/opt/oracle/admin/XE/xdb_wallet))(Presentation=HTTP)(Session=RAW))
Services Summary...
Service "XE" has 1 instance(s).
  Instance "XE", status READY, has 1 handler(s) for this service...
Service "d74d243c27550afae055000000000001" has 1 instance(s).
  Instance "XE", status READY, has 1 handler(s) for this service...
Service "xepdb1" has 1 instance(s).
  Instance "XE", status READY, has 1 handler(s) for this service...
```

Notice particularly:

```
Service "XE" has 1 instance(s).
  Instance "XE", status READY, has 1 handler(s) for this service...
```

There you see that there is a service called `XE` that connects to the instance `XE`.

How to create such a new service? Well, I'm glad to ask, it's really simple!
Just connect to your database as an admin user (e.g. `SYSTEM`) and create and start a new service via the [`DBMS_SERVICE`](https://docs.oracle.com/en/database/oracle/oracle-database/21/arpls/DBMS_SERVICE.html#GUID-386E183E-D83C-48A7-8BA3-40248CFB89F4) package:

## Using a service

### Create new service

```
bash-4.4$ sqlplus system@localhost/XEPDB1

SQL*Plus: Release 21.0.0.0.0 - Production on Sat Mar 5 19:57:52 2022
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle.  All rights reserved.

Enter password:
Last Successful login time: Sat Mar 05 2022 19:53:58 +00:00

Connected to:
Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0

SQL> exec dbms_service.create_service('my_new_service','my_new_service');

PL/SQL procedure successfully completed.
```

### Start new service

```
SQL> exec dbms_service.start_service('my_new_service');

PL/SQL procedure successfully completed.

SQL> exit
Disconnected from Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0
bash-4.4$
```

### Connect via new service

```
bash-4.4$ sqlplus system@localhost/my_new_service

SQL*Plus: Release 21.0.0.0.0 - Production on Sat Mar 5 19:58:36 2022
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle.  All rights reserved.

Enter password:
Last Successful login time: Sat Mar 05 2022 19:57:54 +00:00

Connected to:
Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0

SQL>
```

### See new service in `lsnrctl status`

```
bash-4.4$ lsnrctl status

LSNRCTL for Linux: Version 21.0.0.0.0 - Production on 05-MAR-2022 19:59:44

Copyright (c) 1991, 2021, Oracle.  All rights reserved.

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC_FOR_XE)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 21.0.0.0.0 - Production
Start Date                05-MAR-2022 19:49:37
Uptime                    0 days 0 hr. 10 min. 6 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Default Service           XE
Listener Parameter File   /opt/oracle/homes/OraDBHome21cXE/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/5775acfe2c25/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC_FOR_XE)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=5775acfe2c25)(PORT=5500))(Security=(my_wallet_directory=/opt/oracle/admin/XE/xdb_wallet))(Presentation=HTTP)(Session=RAW))
Services Summary...
Service "XE" has 1 instance(s).
  Instance "XE", status READY, has 1 handler(s) for this service...
Service "d74d243c27550afae055000000000001" has 1 instance(s).
  Instance "XE", status READY, has 1 handler(s) for this service...
Service "my_new_service" has 1 instance(s).
  Instance "XE", status READY, has 1 handler(s) for this service...
Service "xepdb1" has 1 instance(s).
  Instance "XE", status READY, has 1 handler(s) for this service...
The command completed successfully
```

## Create new PDB which comes also with a service

For your needs, however, you could probably also just use `-e ORACLE_DATABASE =<>` which will create a new pluggable database that will also have a service with the same name created:

```
[gvenzl@localhost ~]$ podman run --name test -p 1521:1521 -e ORACLE_PASSWORD=LetsTest1 -e ORACLE_DATABASE=MY_NEW_DB gvenzl/oracle-xe:21-slim
CONTAINER: starting up...
CONTAINER: first database startup, initializing...
CONTAINER: uncompressing database data files, please wait...
CONTAINER: done uncompressing database data files, duration: 25 seconds.
CONTAINER: starting up Oracle Database...
...
...
...
CONTAINER: Creating pluggable database.

Pluggable database created.


Pluggable database altered.


Pluggable database altered.


System altered.

CONTAINER: DONE: Creating pluggable database, duration: 15 seconds.

#########################
DATABASE IS READY TO USE!
#########################
```

```
[gvenzl@localhost ~]$ podman exec -ti test bash
bash-4.4$ sqlplus system@localhost/MY_NEW_DB

SQL*Plus: Release 21.0.0.0.0 - Production on Sat Mar 5 20:03:54 2022
Version 21.3.0.0.0

Copyright (c) 1982, 2021, Oracle.  All rights reserved.

Enter password:
Last Successful login time: Sat Feb 05 2022 21:32:46 +00:00

Connected to:
Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
Version 21.3.0.0.0

SQL>
```

Hope this helps!

**Comment by pidario** [comment]
Thanks for the tip, @gvenzl I'll try to implement it.
For me the issue can be closed 😉
